### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by mfornasa** [danielfm/kube-ecr-cleanup-controller#2]
Not clear to me how to build the project. Can you provide instructions?

**Comment by danielfm** [comment]
Assuming you have your Go environment already configured:

1. Clone this repository in `$GOPATH/src/github.com/danielfm/kube-ecr-cleanup-controller`
2. Run `glide i --strip-vendor` and then `make` to build the binary (or `make image` to build the docker image)
3. Then, just re-tag the image to `<your-name>/kube-ecr-cleanup-controller:<tag>` and push to your own registry, if you feel like it

Or, you can use a pre-built image hosted in Docker Hub:
https://hub.docker.com/r/danielfm/kube-ecr-cleanup-controller/
